name: coconut_chronicles
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0
  tuple: ^2.0.1
  package_info_plus: ^3.0.3
  shared_preferences: ^2.1.0
  encrypt: ^5.0.1
  sqflite: ^2.2.4+1
  country_picker: ^2.0.20
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
