name: coconut_chronicles
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0
  tuple: ^2.0.1
  package_info_plus: ^3.0.3
  shared_preferences: ^2.0.18
  encrypt: ^5.0.1
  sqflite: ^2.2.4+1
  calendar_date_picker2: ^0.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
